---
- name: el | Installing mdadm package
  ansible.builtin.yum:
    name: "{{ item }}"
    state: present
  with_items: "{{ needed_pkgs }}"
  vars:
    needed_pkgs:
      - mdadm
      - util-linux
      - sgdisk

- name: el | Setting distribution-specific facts
  ansible.builtin.set_fact:
    update_initramfs: dracut -f /boot/initramfs-$(uname -r).img $(uname -r)
    setup_linux_raid: ""
    mdadm_conf: /etc/mdadm.conf
    mdadm_conf_path: /etc/mdadm
