---
# tasks file for ansible-mdadm

- include_tasks: debian.yml
  when: ansible_facts.os_family == "Debian"

- include_tasks: el.yml
  when: ansible_facts.os_family == "RedHat"

- name: main | Ensure {{ mdadm_conf }}'s path exists
  file:
    path: "{{ mdadm_conf_path }}"
    state: directory
  when: mdadm_conf_path is defined

- name: main | Ensure {{ mdadm_conf }} file exists
  copy:
    content: ""
    dest: "{{ mdadm_conf }}"
    force: no

- include_tasks: wipe_disks.yml
  when:
    - mdadm_force_wipe is defined
    - mdadm_force_wipe

- include_tasks: arrays.yml
  loop: "{{ mdadm_arrays }}"
  loop_control:
    loop_var: raid_array_item

# Updates initramfs archives in /boot
- name: main | Updating initramfs
  command: "{{ update_initramfs }}"
